# Generated by Django 3.1.5 on 2021-02-03 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wewager", "0005_auto_20210203_1933"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="user",
        ),
        migrations.AddField(
            model_name="account",
            name="wallet",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="wewager.wallet",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wager",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wager",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
