# Generated by Django 3.1.5 on 2021-02-03 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wewager", "0008_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wewager.team",
            ),
        ),
    ]
