# Generated by Django 3.1.5 on 2021-02-09 00:20

from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("wewager", "0010_auto_20210208_2008"),
    ]

    operations = [
        migrations.AddField(
            model_name="wager",
            name="wager_type",
            field=models.CharField(
                choices=[
                    ("normal", "normal"),
                    ("spread", "spread"),
                    ("moneyline", "moneyline"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="wager",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                max_digits=7,
                validators=[djmoney.models.validators.MinMoneyValidator(0)],
            ),
        ),
    ]
