# Generated by Django 3.1.5 on 2021-04-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wewager', '0016_team_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdata',
            name='description',
        ),
        migrations.AlterField(
            model_name='game',
            name='gameUid',
            field=models.CharField(max_length=64),
        ),
    ]
