# Generated by Django 3.1.5 on 2021-04-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wewager', '0017_auto_20210422_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('bet_type', models.CharField(max_length=32)),
                ('bet_price', models.CharField(max_length=5)),
                ('update_dt', models.DateTimeField(auto_now_add=True)),
                ('hit', models.BooleanField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='gameUid',
            new_name='external_uid',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='league',
            field=models.CharField(default='NBA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='outcomes',
            field=models.ManyToManyField(to='wewager.GameOutcome'),
        ),
    ]
