# Generated by Django 3.1.5 on 2021-04-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wewager', '0018_auto_20210423_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameoutcome',
            name='external_uid',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
