# Generated by Django 3.1.5 on 2021-04-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wewager", "0019_gameoutcome_external_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="external_uid",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="gameoutcome",
            name="external_uid",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
