# Generated by Django 3.1.5 on 2021-04-28 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wewager", "0022_game_date_eastern"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ("date",)},
        ),
    ]
