# Generated by Django 3.1.5 on 2021-04-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wewager', '0023_auto_20210428_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdata',
            name='game',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamData',
        ),
    ]
