# Generated by Django 3.1.5 on 2021-04-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wewager", "0024_auto_20210429_2122"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Avatar",
        ),
    ]
