name: Deploy to Production
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CapRover Deploy
        uses: floms/action-caprover@v1
        with:
          host: https://https://captain.next.wewager.io/
          password: ${{ secrets.CAPROVER_PASS }}
          app: api
          branch: main
